### ISSUE TITLE
Companies tag is not working

### ISSUE THREAD

**Issue by nimish-kumar** [binbard/leet-xt#2]
It was working for few seconds but stopped working when I tested again. 

It is not working for 'DE Shaw'

**Comment by David-Singh-Rolson** [comment]
Do not search in searchbar for company name.

![image](https://github.com/binbard/leet-xt/assets/89672924/238a69f8-8be1-42ef-9db7-ca8afcc1229e)

Goto 'De shaw' using arrow buttons

**Comment by Dhruv1238** [comment]
Its not working for me either, clicking on companies just shows this:
![image](https://github.com/binbard/leet-xt/assets/75005930/bdf22aeb-85bc-4c79-80f6-1ed98e40648e)

**Comment by binbard** [comment]
Should've been fixed. Check
