### ISSUE TITLE
Unlock Editorials not working!!

### ISSUE THREAD

**Issue by krish0596** [binbard/leet-xt#3]
Not able to unlock Editorials since the past few weeks!!

**Comment by binbard** [comment]
Wait for a fix, should be fixed before weekend.

**Comment by binbard** [comment]
Wait for next update, should be fixed before weekend.

**Comment by binbard** [comment]
Editorial unlocking is functioning effectively. It may be that those are new problems, not available in crowd-sourced data.

**Comment by binbard** [comment]
Could you provide the problems for which the editorial is not visible?
